### PR TITLE
Topic hotfix and improvements

### PR DESCRIPTION
**Pull request by seprintour**
Resolves #

Should fix this issue https://github.com/ubiquity/ubiquibot-telegram/pull/17#issuecomment-1712892726 from @pavlovcik

### CODE REVIEW

**Comment by 0x4007** [comment]
Let's test

**Comment by seprintour** [comment]
> Let's test

@pavlovcik

**Comment by seprintour** [comment]
> Let's test

@pavlovcik can we test?

**Comment by seprintour** [comment]
ping

**Comment by 0x4007** [comment]
What's the easiest way to test?

**Comment by seprintour** [comment]
> What's the easiest way to test?

The telegram channel you used the last time, with topics

**Review by pavlovcik — APPROVED** [review]
QA looks good. 

- https://t.me/+lOokR0qGjKI5MDQx (topics)
- https://t.me/+MlosSV46qWIxNWUx (no topics)

**Pull request merged**
