### PR TITLE
Misc improvements

### LINKED ISSUE #34: Misc Improvements
1. I changed the bot admin title and it posted the welcome message again https://t.me/UbiquityDAO/1/31176
2. I'm unsure how to register the general topic https://t.me/UbiquityDAO/1/31178 - update: the bot should explain that it's already added and to configure in the settings. 
3. UI no longer usable after several added topics. It no longer responds to button presses:

image

4. Renamed `fundraising` to `partnerships` in https://t.me/UbiquityDAO/29361 and it's not being updated in bot UI

> Here is your forum: Fundraising 
What do you want to do?

### PR DESCRIPTION
**Pull request by seprintour**
Resolves #34

### CODE REVIEW

**Comment by seprintour** [comment]
@pavlovcik

**Review by pavlovcik — CHANGES_REQUESTED** [review]
I've never seen the term forums inside of the telegram UI so you should never use this term either. Perhaps you are referring to topics in which case please rename all the variables to refer to topics.

**Comment by seprintour** [comment]
> I've never seen the term forums inside of the telegram UI so you should never use this term either. Perhaps you are referring to topics in which case please rename all the variables to refer to topics.

Okay, I'd change it.. It's called forum on the API documentation though so I just went with it

**Comment by seprintour** [comment]
> forums

@pavlovcik I think we should leave the variable names as forum.. while communicating with the API, it returns forum. so switching between forum and topic is going to be confusing.

API = forum
UI = topic (we can make bots reply use topic instead of forum so its constant on the UI)

**Comment by 0x4007** [comment]
> (we can make bots reply use topic instead of forum so its constant on the UI)

Agreed

**Comment by seprintour** [comment]
> > (we can make bots reply use topic instead of forum so its constant on the UI)
> 
> Agreed

Done, moved all API to forum and made sure to return topic on UI

**Review by pavlovcik — APPROVED** [review]

**Pull request merged**
